# site settings
title: Datalogues
subtitle: by Monica Powell
email: monica@aboutmonica.com
description: An exploration of various areas of data visualization and programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
image: "http://www.datalogues.com/assets/images/home-bg.jpg"
author: Monica Powell
# street_address: 1234 Somewhere Road
city: Brooklyn
state: New York
# zip_code: 55555
# country: United States of America
# phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: http://www.github.com/m0nica
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/monicampowell/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/waterproofheart

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
